version: "3.5"

services:
  mongodb-housing-system:
    container_name: mongodb-housing-system
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb-data-housing-system:/data/db
    networks:
      - network-housing-system

  node-housing-system:
    container_name: node-housing-system
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 5000:5000
    depends_on:
      - mongodb-housing-system
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb-housing-system
      DB_NAME: housing_system
    networks:
      - network-housing-system

  mongo-express-housing-system:
    image: mongo-express
    depends_on:
      - mongodb-housing-system
    ports:
      - 8077:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb-housing-system
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123456
    networks:
      - network-housing-system

  website-housing-system:
    restart: always
    build:
      context: ./website
      dockerfile: Dockerfile
    container_name: website-housing-system
    volumes:
      - ./website:/app
      - ./website/node_modules:/app/node_modules 
    depends_on:
      - node-housing-system
    ports:
      - 3000:3000
    networks:
      - network-housing-system

networks:
  network-housing-system:
    driver: bridge

volumes:
  mongodb-data-housing-system:
